// Canonical list of supported locations and travel fees
// Shared by Property Settings and Cleaning Bills

export const LOCATIONS = [
  'Água de Pena',
  'Arco da Calheta',
  'Arco de São Jorge',
  'Calheta',
  'Câmara de Lobos',
  'Caniçal',
  'Caniço',
  'Fajã da Ovelha',
  'Funchal',
  'Gaula',
  'Ilha',
  'Machico',
  'Madalena do Mar',
  'Paul do Mar',
  'Ponta Delgada',
  'Ponta do Sol',
  'Porto Moniz',
  'Porto Novo',
  'Ribeira Brava',
  'Ribeira da Janela',
  'Santa Cruz',
  'Santa do Porto Moniz',
  'Santana',
  'São Jorge',
  'São Vicente'
];

// Travel fees per location, aligned to LOCATIONS above
export const TRAVEL_FEES = {
  'Água de Pena': 18.00,
  'Arco da Calheta': 22.00,
  'Arco de São Jorge': 30.00,
  'Calheta': 19.00,
  'Câmara de Lobos': 5.00,
  'Caniçal': 22.00,
  'Caniço': 11.00,
  'Fajã da Ovelha': 27.00,
  'Funchal': 5.00,
  'Gaula': 15.00,
  'Ilha': 37.00,
  'Machico': 20.00,
  'Madalena do Mar': 13.00,
  'Paul do Mar': 31.00,
  'Ponta Delgada': 23.00,
  'Ponta do Sol': 13.00,
  'Porto Moniz': 31.00,
  'Porto Novo': 15.00,
  'Ribeira Brava': 8.00,
  'Ribeira da Janela': 37.00,
  'Santa Cruz': 16.00,
  'Santa do Porto Moniz': 33.00,
  'Santana': 33.00,
  'São Jorge': 34.00,
  'São Vicente': 20.00,
};
