import { run } from "./test-harness.js";

import "./unit/core/config.test.js";
import "./unit/core/i18n.test.js";
import "./unit/shared/change-notifier.test.js";
import "./unit/shared/access-roles.test.js";
import "./unit/shared/email.test.js";
import "./unit/shared/enums.test.js";
import "./unit/shared/locations.test.js";
import "./unit/features/admin/access-linking.test.js";
import "./unit/features/admin/user-management-controller.test.js";
import "./unit/features/operations/cleaning-ah-utils.test.js";
import "./unit/features/operations/cleaning-bills-manager.test.js";
import "./unit/features/operations/commission-calculator-manager.test.js";
import "./unit/features/operations/welcome-pack-manager.test.js";
import "./unit/features/properties/property-form-utils.test.js";
import "./unit/features/properties/properties-dashboard-controller.test.js";
import "./unit/features/scheduling/attendance-print-period.test.js";
import "./unit/features/scheduling/attendance-records.test.js";
import "./unit/features/scheduling/employee-records.test.js";
import "./unit/features/scheduling/holiday-calculator.test.js";
import "./unit/features/scheduling/navigation-manager.test.js";
import "./unit/features/scheduling/time-clock-controls.test.js";
import "./unit/features/scheduling/time-clock-station.test.js";
import "./unit/features/scheduling/vacation-board-view-model.test.js";
import "./unit/features/scheduling/vacation-records.test.js";
import "./smoke/html-pages.test.js";
import "./smoke/locales.test.js";

const results = await run();
const total = results.reduce((sum, suite) => sum + suite.tests.length, 0);
const failed = results.reduce((sum, suite) => sum + suite.tests.filter((test) => !test.pass).length, 0);
document.title = failed === 0 ? `PASS ${total}` : `FAIL ${failed}/${total}`;
window.__testResults = results;
